## IMPORT MODULES
## IMPORT MODULES
## IMPORT MODULES

## BEGIN FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE
## BEGIN FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE
## BEGIN FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE

def fn_TupleOfWordsAndGematriaValuesCreate(ListOfWords, NW):
    
    ## TEST PRINT OUTPUT
    #print("\n")  ## PRINT SPACE
    #print("WITHIN FUNCTION:  BEGIN FUNCTION #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE ")
          
    ## DECLARE VARIABLES
    ## CALL PYTHON BUILT-IN FUNCTION(S) - CREATE TUPLE OF WORDS AND GEMATRIA VALUES

    W = tuple(zip(ListOfWords, NW))
    
    ## TEST PRINT OUTPUT        
    ## print(W)
    
    ## TEST PRINT OUTPUT
    #print("\n")  ## PRINT SPACE
    #print("WITHIN FUNCTION:  END FUNCTION #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE")
    
    ## RETURN VARIABLES - TUPLE OF WORDS AND GEMATRIA VALUES
    return(W)
    
## END FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE
## END FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE
## END FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE


