## IMPORT MODULES

## BEGIN FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE

def fn_TupleOfWordsAndGematriaValuesCreate(ListOfWords, NW, ListOfIndexesCustom, ListOfIndexes4LettersInEachWord): ## NW == TUPLE OF (LIST, INTEGER)
    
    """
    ## MODULE.FUNCTION() #11 - DATA OBJECT CREATE - RETURNS TUPLE OF WORDS WITH EACH WORD'S GEMATRIA NUMBER VALUE
    """

    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  BEGIN FUNCTION #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE ")
          
    ## DECLARE VARIABLES
    ## CALL PYTHON BUILT-IN FUNCTION(S) - CREATE TUPLE OF WORDS, LETTER POSITIONS, WORD#, GEMATRIA VALUES FOR LETTER, GEMATRIA VALUE SUM FOR ENTIRE WORD

    ## CREATE W
    if ListOfIndexes4LettersInEachWord == []: ## IF THE PARAMETERS ARE FOR THE ELSs, THEN WE USE THE DEFAULT VALUE OF EMPTY LIST

        W = tuple(zip(ListOfWords, NW))

    else: ## ELSE WE ARE PASSING THE ENTIRE TEXT, AND THEREFORE NEED THE INDEX POSITIONS OF EACH LETTER

        W = tuple(zip(ListOfWords, ListOfIndexes4LettersInEachWord, NW))

    
    ## CREATE DICT OF W
    DW = dict(zip(ListOfIndexesCustom, W))
    
    ## TEST PRINT OUTPUT        
    ## print(W)
    
    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  END FUNCTION #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE")
    
    ## RETURN VARIABLES - TUPLE OF WORDS AND GEMATRIA VALUES
    return(W, DW)
    
## END FUNCTION () #11 - TUPLE OF WORDS AND GEMATRIA VALUES CREATE


