## IMPORT MODULES

## DEFINE FUNCTION
def fn_AddSearchResultsToDELSO(DELSO, DELSMP, DELSMN):

    """ ## MODULE.FUNCTION() #24 - ## RETURNS: DELSO """

    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  BEGIN FUNCTION #24 - ADD ELS SEARCH RESULTS TO DELSO")

    ## ADD ELS SEARCH RESULTS TO EACH ELS OBJECT (ELSO) IN DICTIONARY OF ELS OBJECTS (DELSO)

    ## DECLARE VARIABLES - FOR FOR LOOP BELOW WITH 1-INDEX DELSO OBJECT
    CurrentDictKeyPosition = 1

    ## ADDING LETTER NUMBER VALUE PROPERTY VALUE TO EACH INSTANCE OF LETTER OBJECT
    for EachELSObject in DELSO.values():

        ## ADD VALUE OF NUMBER TO INSTANCE OF LETTER OBJECT
        EachELSObject.DELSMP = DELSMP[CurrentDictKeyPosition] ## ADD DICT OF POSITIVE ELS MATCHES TO DELSO
        EachELSObject.NMP = len(DELSMP[CurrentDictKeyPosition])
        EachELSObject.DELSMN = DELSMN[CurrentDictKeyPosition] ## ADD DICT OF NEGATIVE ELS MATCHES TO DELSO
        EachELSObject.NMN = len(DELSMN[CurrentDictKeyPosition])

        ## INCREMENT
        CurrentDictKeyPosition += 1

    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  END FUNCTION #24 - ADD ELS SEARCH RESULTS TO DELSO")

    ## RETURN VARIABLES
    return(DELSO)