## IMPORT MODULES

## DEFINE FUNCTION ##
def fn_AddSearchResultsToDELSO(DELSO, DELSMLF_POS, DELSMLF_NEG, DELSMLL_POS, DELSMLL_NEG):

    """ ## MODULE.FUNCTION() #24 - ## RETURNS: DELSO """

    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  BEGIN FUNCTION #24 - ADD ELS SEARCH RESULTS TO DELSO")

    ## ADD ELS SEARCH RESULTS TO EACH ELS OBJECT (ELSO) IN DICTIONARY OF ELS OBJECTS (DELSO)

    ## DECLARE VARIABLES - FOR FOR LOOP BELOW WITH 1-INDEX DELSO OBJECT
    CurrentDictKeyPosition = 1

    ## ADDING LETTER NUMBER VALUE PROPERTY VALUE TO EACH INSTANCE OF LETTER OBJECT
    for EachELSObject in DELSO.values():

        ## ADD VALUE OF NUMBER TO INSTANCE OF LETTER OBJECT
        EachELSObject.DELSMLF_POS = DELSMLF_POS[CurrentDictKeyPosition] ## ADD DICT OF POSITIVE ELS MATCHES TO DELSO BY LETTER FIRST
        EachELSObject.DELSMLF_NEG = DELSMLF_NEG[CurrentDictKeyPosition] ## ADD DICT OF NEGATIVE ELS MATCHES TO DELSO BY LETTER FIRST
        EachELSObject.DELSMLL_POS = DELSMLL_POS[CurrentDictKeyPosition] ## ADD DICT OF POSITIVE ELS MATCHES TO DELSO BY LETTER LAST
        EachELSObject.DELSMLL_NEG = DELSMLL_NEG[CurrentDictKeyPosition] ## ADD DICT OF NEGATIVE ELS MATCHES TO DELSO BY LETTER LAST
        EachELSObject.NMP = len(DELSMLF_POS[CurrentDictKeyPosition])
        EachELSObject.NMN = len(DELSMLF_NEG[CurrentDictKeyPosition])

        ## INCREMENT
        CurrentDictKeyPosition += 1

    ## TEST PRINT OUTPUT
    print("\n")  ## PRINT SPACE
    print("WITHIN FUNCTION:  END FUNCTION #24 - ADD ELS SEARCH RESULTS TO DELSO")

    ## RETURN VARIABLES
    return(DELSO)