## IMPORT MODULES
## IMPORT MODULES
## IMPORT MODULES

import mod_GetUserInput1 ## MODULE.FUNCTION() #1 - GET USER INPUT; CHOOSE TEXT TO SEARCH
import mod_TextFileOpen ## MODULE.FUNCTION() #2 - TEXT FILE OPEN
import mod_TextFilePreprocess ## MODULE.FUNCTION() #3A - TEXT FILE PREPROCESS; CALLS MODULE.FUNCTION() #3B - TEXT FILE PARSE
import mod_ConvertJSONStringsToDicts ## MODULE.FUNCTION() #4 - CONVERT PARSED JSON STRINGS TO LIST OF DICTS
import mod_GetNumberOfTextChosen ## MODULE.FUNCTION() #5 - GET NUMBER OF TEXT CHOSEN
import mod_TextDictionaryCreateA ## MODULE.FUNCTION() #6A - TEXT DICTIONARY CREATE A; CALLS MODULE.FUNCTION() #6B - TEXT DICTIONARY CREATE B
#import mod_GetUserInput2 ## MODULE.FUNCTION() # - GET USER INPUT; INPUT ELS SEARCH TERM
import pprint

## DECLARE VARIABLES
## DECLARE VARIABLES
## DECLARE VARIABLES

## N = START POSITION OF ELS IN STRING/LIST/DICTIONARY

## D = LENGTH OF SKIP BETWEEN LETTERS IN ELS

## K = LENGTH OF ELS: i.e. SEARCH TERM // USER INPUT 2

## BEGIN MAIN PROGRAM
## BEGIN MAIN PROGRAM
## BEGIN MAIN PROGRAM

## CALL MODULES.FUNCTIONS
## CALL MODULES.FUNCTIONS
## CALL MODULES.FUNCTIONS

## CALL MODULE.FUNCTION() #1 - GET USER INPUT 1 - CHOOSE TEXT TO SEARCH
TextChosen = mod_GetUserInput1.fn_GetUserInput1()

## CALL MODULE.FUNCTION() #2 - TEXT FILE OPEN
JSON = mod_TextFileOpen.fn_TextFileOpen(TextChosen)

## CALL MODULE.FUNCTION() #3A - TEXT FILE PREPROCESS; CALLS MODULE.FUNCTION() #3B - TEXT FILE PARSE
ListOfJSONStringsParsed = mod_TextFilePreprocess.fn_TextFilePreprocess(JSON)

## CALL MODULE.FUNCTION() #4 - CONVERT PARSED JSON STRINGS TO DICTIONARIES; RETURN LIST OF DICTIONARIES
ListOfDictsOfJSONStringsParsed = mod_ConvertJSONStringsToDicts.fn_ConvertJSONStringsToDicts(ListOfJSONStringsParsed)

## CALL MODULE.FUNCTION() #5 - GET NUMBER OF TEXT CHOSEN
SearchTextChosen = mod_GetNumberOfTextChosen.fn_GetNumberOfTextChosen(ListOfDictsOfJSONStringsParsed)

## CALL MODULE.FUNCTION() #6A - TEXT DICTIONARY CREATE A; CALLS MODULE.FUNCTION() #6B - TEXT DICTIONARY CREATE B
DictOfVerses = mod_TextDictionaryCreateA.fn_TextDictionaryCreateA(ListOfDictsOfJSONStringsParsed, SearchTextChosen)




## CALL MODULE.FUNCTION() # - GET USER INPUT 2 - INPUT TEXT EQUIDISTANT LETTER SEQUENCES (ELS = K) TO SEARCH
# UserInput2 = mod_GetUserInput2.fn_GetUserInput2()



## END MAIN PROGRAM
## END MAIN PROGRAM
## END MAIN PROGRAM

## GAME OVER
## GAME OVER
## GAME OVER
